name: Scrape and Push

on:
  push:
  schedule:
    - cron: '0 0 * * 5'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install .
      - run: ./bin/qanda > qanda.xml
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add qanda.xml qanda-state.json
          git commit -m 'qanda: scrape'
          git push
